#include "posix-wasm.h"

#undef HAVE_CHROOT
#undef HAVE__LOCALTIME64_S
#undef HAVE_LOCALTIME_R
#undef HAVE__CTIME64_S
#undef HAVE__GMTIME64_S
#undef HAVE_FUTIMESAT
#undef HAVE_FUTIMES
#undef HAVE_READPASSPHRASE
#undef HAVE_FLISTXATTR
#undef ARCHIVE_XATTR_LINUX
#undef HAVE_GETGRGID_R
#undef HAVE_GETGRNAM_R
#undef HAVE_LUTIMES
